/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BillingSubscribeRouteImport } from './routes/billing.subscribe'
import { Route as BillingCallbackRouteImport } from './routes/billing.callback'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthShopifyInstallRouteImport } from './routes/auth.shopify.install'
import { Route as AuthShopifyCallbackRouteImport } from './routes/auth.shopify.callback'
import { Route as ApiShopifySessionPingRouteImport } from './routes/api.shopify.session-ping'
import { Route as ApiPublicProcessPendingOrdersRouteImport } from './routes/api.public.process-pending-orders'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWebhooksShopifyOrdersCreateRouteImport } from './routes/api.public.webhooks.shopify.orders-create'
import { Route as ApiPublicWebhooksShopifyComplianceRouteImport } from './routes/api.public.webhooks.shopify.compliance'
import { Route as ApiPublicWebhooksShopifyAppUninstalledRouteImport } from './routes/api.public.webhooks.shopify.app-uninstalled'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSubscribeRoute = BillingSubscribeRouteImport.update({
  id: '/billing/subscribe',
  path: '/billing/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCallbackRoute = BillingCallbackRouteImport.update({
  id: '/billing/callback',
  path: '/billing/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthShopifyInstallRoute = AuthShopifyInstallRouteImport.update({
  id: '/auth/shopify/install',
  path: '/auth/shopify/install',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthShopifyCallbackRoute = AuthShopifyCallbackRouteImport.update({
  id: '/auth/shopify/callback',
  path: '/auth/shopify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifySessionPingRoute = ApiShopifySessionPingRouteImport.update({
  id: '/api/shopify/session-ping',
  path: '/api/shopify/session-ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProcessPendingOrdersRoute =
  ApiPublicProcessPendingOrdersRouteImport.update({
    id: '/api/public/process-pending-orders',
    path: '/api/public/process-pending-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksShopifyOrdersCreateRoute =
  ApiPublicWebhooksShopifyOrdersCreateRouteImport.update({
    id: '/api/public/webhooks/shopify/orders-create',
    path: '/api/public/webhooks/shopify/orders-create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksShopifyComplianceRoute =
  ApiPublicWebhooksShopifyComplianceRouteImport.update({
    id: '/api/public/webhooks/shopify/compliance',
    path: '/api/public/webhooks/shopify/compliance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksShopifyAppUninstalledRoute =
  ApiPublicWebhooksShopifyAppUninstalledRouteImport.update({
    id: '/api/public/webhooks/shopify/app-uninstalled',
    path: '/api/public/webhooks/shopify/app-uninstalled',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/billing/callback': typeof BillingCallbackRoute
  '/billing/subscribe': typeof BillingSubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/process-pending-orders': typeof ApiPublicProcessPendingOrdersRoute
  '/api/shopify/session-ping': typeof ApiShopifySessionPingRoute
  '/auth/shopify/callback': typeof AuthShopifyCallbackRoute
  '/auth/shopify/install': typeof AuthShopifyInstallRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/webhooks/shopify/app-uninstalled': typeof ApiPublicWebhooksShopifyAppUninstalledRoute
  '/api/public/webhooks/shopify/compliance': typeof ApiPublicWebhooksShopifyComplianceRoute
  '/api/public/webhooks/shopify/orders-create': typeof ApiPublicWebhooksShopifyOrdersCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/billing/callback': typeof BillingCallbackRoute
  '/billing/subscribe': typeof BillingSubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/process-pending-orders': typeof ApiPublicProcessPendingOrdersRoute
  '/api/shopify/session-ping': typeof ApiShopifySessionPingRoute
  '/auth/shopify/callback': typeof AuthShopifyCallbackRoute
  '/auth/shopify/install': typeof AuthShopifyInstallRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/webhooks/shopify/app-uninstalled': typeof ApiPublicWebhooksShopifyAppUninstalledRoute
  '/api/public/webhooks/shopify/compliance': typeof ApiPublicWebhooksShopifyComplianceRoute
  '/api/public/webhooks/shopify/orders-create': typeof ApiPublicWebhooksShopifyOrdersCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/billing/callback': typeof BillingCallbackRoute
  '/billing/subscribe': typeof BillingSubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/process-pending-orders': typeof ApiPublicProcessPendingOrdersRoute
  '/api/shopify/session-ping': typeof ApiShopifySessionPingRoute
  '/auth/shopify/callback': typeof AuthShopifyCallbackRoute
  '/auth/shopify/install': typeof AuthShopifyInstallRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/webhooks/shopify/app-uninstalled': typeof ApiPublicWebhooksShopifyAppUninstalledRoute
  '/api/public/webhooks/shopify/compliance': typeof ApiPublicWebhooksShopifyComplianceRoute
  '/api/public/webhooks/shopify/orders-create': typeof ApiPublicWebhooksShopifyOrdersCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/unsubscribe'
    | '/billing/callback'
    | '/billing/subscribe'
    | '/email/unsubscribe'
    | '/api/public/process-pending-orders'
    | '/api/shopify/session-ping'
    | '/auth/shopify/callback'
    | '/auth/shopify/install'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/webhooks/shopify/app-uninstalled'
    | '/api/public/webhooks/shopify/compliance'
    | '/api/public/webhooks/shopify/orders-create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/unsubscribe'
    | '/billing/callback'
    | '/billing/subscribe'
    | '/email/unsubscribe'
    | '/api/public/process-pending-orders'
    | '/api/shopify/session-ping'
    | '/auth/shopify/callback'
    | '/auth/shopify/install'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/webhooks/shopify/app-uninstalled'
    | '/api/public/webhooks/shopify/compliance'
    | '/api/public/webhooks/shopify/orders-create'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/unsubscribe'
    | '/billing/callback'
    | '/billing/subscribe'
    | '/email/unsubscribe'
    | '/api/public/process-pending-orders'
    | '/api/shopify/session-ping'
    | '/auth/shopify/callback'
    | '/auth/shopify/install'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/webhooks/shopify/app-uninstalled'
    | '/api/public/webhooks/shopify/compliance'
    | '/api/public/webhooks/shopify/orders-create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  BillingCallbackRoute: typeof BillingCallbackRoute
  BillingSubscribeRoute: typeof BillingSubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicProcessPendingOrdersRoute: typeof ApiPublicProcessPendingOrdersRoute
  ApiShopifySessionPingRoute: typeof ApiShopifySessionPingRoute
  AuthShopifyCallbackRoute: typeof AuthShopifyCallbackRoute
  AuthShopifyInstallRoute: typeof AuthShopifyInstallRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicWebhooksShopifyAppUninstalledRoute: typeof ApiPublicWebhooksShopifyAppUninstalledRoute
  ApiPublicWebhooksShopifyComplianceRoute: typeof ApiPublicWebhooksShopifyComplianceRoute
  ApiPublicWebhooksShopifyOrdersCreateRoute: typeof ApiPublicWebhooksShopifyOrdersCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/subscribe': {
      id: '/billing/subscribe'
      path: '/billing/subscribe'
      fullPath: '/billing/subscribe'
      preLoaderRoute: typeof BillingSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/callback': {
      id: '/billing/callback'
      path: '/billing/callback'
      fullPath: '/billing/callback'
      preLoaderRoute: typeof BillingCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/shopify/install': {
      id: '/auth/shopify/install'
      path: '/auth/shopify/install'
      fullPath: '/auth/shopify/install'
      preLoaderRoute: typeof AuthShopifyInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/shopify/callback': {
      id: '/auth/shopify/callback'
      path: '/auth/shopify/callback'
      fullPath: '/auth/shopify/callback'
      preLoaderRoute: typeof AuthShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/session-ping': {
      id: '/api/shopify/session-ping'
      path: '/api/shopify/session-ping'
      fullPath: '/api/shopify/session-ping'
      preLoaderRoute: typeof ApiShopifySessionPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/process-pending-orders': {
      id: '/api/public/process-pending-orders'
      path: '/api/public/process-pending-orders'
      fullPath: '/api/public/process-pending-orders'
      preLoaderRoute: typeof ApiPublicProcessPendingOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/shopify/orders-create': {
      id: '/api/public/webhooks/shopify/orders-create'
      path: '/api/public/webhooks/shopify/orders-create'
      fullPath: '/api/public/webhooks/shopify/orders-create'
      preLoaderRoute: typeof ApiPublicWebhooksShopifyOrdersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/shopify/compliance': {
      id: '/api/public/webhooks/shopify/compliance'
      path: '/api/public/webhooks/shopify/compliance'
      fullPath: '/api/public/webhooks/shopify/compliance'
      preLoaderRoute: typeof ApiPublicWebhooksShopifyComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/shopify/app-uninstalled': {
      id: '/api/public/webhooks/shopify/app-uninstalled'
      path: '/api/public/webhooks/shopify/app-uninstalled'
      fullPath: '/api/public/webhooks/shopify/app-uninstalled'
      preLoaderRoute: typeof ApiPublicWebhooksShopifyAppUninstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  BillingCallbackRoute: BillingCallbackRoute,
  BillingSubscribeRoute: BillingSubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicProcessPendingOrdersRoute: ApiPublicProcessPendingOrdersRoute,
  ApiShopifySessionPingRoute: ApiShopifySessionPingRoute,
  AuthShopifyCallbackRoute: AuthShopifyCallbackRoute,
  AuthShopifyInstallRoute: AuthShopifyInstallRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicWebhooksShopifyAppUninstalledRoute:
    ApiPublicWebhooksShopifyAppUninstalledRoute,
  ApiPublicWebhooksShopifyComplianceRoute:
    ApiPublicWebhooksShopifyComplianceRoute,
  ApiPublicWebhooksShopifyOrdersCreateRoute:
    ApiPublicWebhooksShopifyOrdersCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
